        let str ='hi java script';
        str1= str.toUpperCase();
        console.log(str1);
        str2 = str.toLowerCase();
        console.log(str2);
        str3 = str.charAt(3);
        console.log(str3);
        str4 = str.indexOf('ja',3);
        console.log(str4);
        str5 = str.concat(' hello')
        console.log(str5);
        str6 = str.includes('va',4);
        console.log(str6);
        str7 = str.replace('hi','hello');
        console.log(str7);
        str8 = str.search('scr');
        console.log(str8);
        str9 =str.trim();
        console.log(str9);
        str10 = str.substr(0,3);
        console.log(str10);
        str11 = str.split('0');
        console.log(str11);
        str12 = str.split('j',2);
        console.log(str12);
console.log('==========================================');
let stri ='hello java ';
        str1= stri.toUpperCase();
        console.log(str1);
        str2 = stri.toLowerCase();
        console.log(str2);
        str3 = stri.charAt(3);
        console.log(str3);
        str4 = stri.indexOf('ja',3);
        console.log(str4);
        str5 = stri.concat(' sql')
        console.log(str5);
        str6 = stri.includes('ja',4);
        console.log(str6);
        str7 = stri.replace('java','j2ee');
        console.log(str7);
        str8 = stri.search('va');
        console.log(str8);
        str9 =stri.trim();
        console.log(str9);
        str10 = stri.substr(0,3);
        console.log(str10);
        str11 = stri.split('o');
        console.log(str11);
        str12 = stri.split('j',2);
        console.log(str12);
        console.log('===============================================');
        let st ='mahesh babu';
        str1= st.toUpperCase();
        console.log(str1);
        str2 = st.toLowerCase();
        console.log(str2);
        str3 = st.charAt(3);
        console.log(str3);
        str4 = st.indexOf('sh',3);
        console.log(str4);
        str5 = st.concat(' , super star')
        console.log(str5);
        str6 = st.includes('ba',4);
        console.log(str6);
        str7 = st.replace('mahesh','mahi');
        console.log(str7);
        str8 = st.search('ma');
        console.log(str8);
        str9 =st.trim();
        console.log(str9);
        str10 = st.substr(0,3);
        console.log(str10);
        str11 = st.split('h');
        console.log(str11);
        str12 = st.split('b',2);
        console.log(str12);
        console.log('=========================================================')
        let stg ='im learning javascript';
        str1= stg.toUpperCase();
        console.log(str1);
        str2 = stg.toLowerCase();
        console.log(str2);
        str3 = stg.charAt(3);
        console.log(str3);
        str4 = stg.indexOf('sc',3);
        console.log(str4);
        str5 = stg.concat(' hi')
        console.log(str5);
        str6 = stg.includes('ja',4);
        console.log(str6);
        str7 = stg.replace('javascript','html');
        console.log(str7);
        str8 = stg.search('ea');
        console.log(str8);
        str9 =stg.trim();
        console.log(str9);
        str10 = stg.substr(0,3);
        console.log(str10);
        str11 = stg.split('a');
        console.log(str11);
        str12 = stg.split('j',2);
        console.log(str12);
        console.log('=======================================================')
        let stv ='watching movies';
        str1= stv.toUpperCase();
        console.log(str1);
        str2 = stv.toLowerCase();
        console.log(str2);
        str3 = stv.charAt(3);
        console.log(str3);
        str4 = stv.indexOf('ch',3);
        console.log(str4);
        str5 = stv.concat(' im')
        console.log(str5);
        str6 = stv.includes('in',4);
        console.log(str6);
        str7 = stv.replace('movies','films');
        console.log(str7);
        str8 = stv.search('ie');
        console.log(str8);
        str9 =stv.trim();
        console.log(str9);
        str10 = stv.substr(0,3);
        console.log(str10);
        str11 = stv.split('s');
        console.log(str11);
        str12 = stv.split('s',2);
        console.log(str12);
        console.log('=======================================================')
        let stl ='folwers are beutiful';
        str1= stl.toUpperCase();
        console.log(str1);
        str2 = stl.toLowerCase();
        console.log(str2);
        str3 = stl.charAt(3);
        console.log(str3);
        str4 = stl.indexOf('e',3);
        console.log(str4);
        str5 = stl.concat(' beautiful')
        console.log(str5);
        str6 = stl.includes('in',4);
        console.log(str6);
        str7 = stl.replace('beutiful','attractive');
        console.log(str7);
        str8 = stl.search('if');
        console.log(str8);
        str9 =stl.trim();
        console.log(str9);
        str10 = stl.substr(0,3);
        console.log(str10);
        str11 = stl.split('s');
        console.log(str11);
        str12 = stl.split('o',2);
        console.log(str12);
        console.log('=======================================================')
        let stn ='i like cricket';
        str1= stn.toUpperCase();
        console.log(str1);
        str2 = stn.toLowerCase();
        console.log(str2);
        str3 = stn.charAt(3);
        console.log(str3);
        str4 = stn.indexOf('ke',3);
        console.log(str4);
        str5 = stn.concat(' love')
        console.log(str5);
        str6 = stn.includes('s',4);
        console.log(str6);
        str7 = stn.replace('cricket','volleyball');
        console.log(str7);
        str8 = stn.search('ke');
        console.log(str8);
        str9 =stn.trim();
        console.log(str9);
        str10 = stn.substr(0,3);
        console.log(str10);
        str11 = stn.split('e');
        console.log(str11);
        str12 = stn.split('c',2);
        console.log(str12);
        console.log('=======================================================')
        let stm ='rainbow';
        str1= stm.toUpperCase();
        console.log(str1);
        str2 = stm.toLowerCase();
        console.log(str2);
        str3 = stm.charAt(3);
        console.log(str3);
        str4 = stm.indexOf('bo',3);
        console.log(str4);
        str5 = stm.concat(' nice')
        console.log(str5);
        str6 = stm.includes('s',7);
        console.log(str6);
        str7 = stm.replace('rainbow','7colors');
        console.log(str7);
        str8 = stm.search('nb');
        console.log(str8);
        str9 =stm.trim();
        console.log(str9);
        str10 = stm.substr(0,3);
        console.log(str10);
        str11 = stm.split('n');
        console.log(str11);
        str12 = stm.split('b',2);
        console.log(str12);
        console.log('=======================================================')
        let sth ='long trip to traval';
        str1= sth.toUpperCase();
        console.log(str1);
        str2 = sth.toLowerCase();
        console.log(str2);
        str3 = sth.charAt(3);
        console.log(str3);
        str4 = sth.indexOf('ip',3);
        console.log(str4);
        str5 = sth.concat(' go')
        console.log(str5);
        str6 = sth.includes('way',4);
        console.log(str6);
        str7 = sth.replace('traval','travalling');
        console.log(str7);
        str8 = sth.search('to');
        console.log(str8);
        str9 =sth.trim();
        console.log(str9);
        str10 = sth.substr(0,3);
        console.log(str10);
        str11 = sth.split('p');
        console.log(str11);
        str12 = sth.split('p',2);
        console.log(str12);
        console.log('=======================================================')
        let stu ='playing games';
        str1= stu.toUpperCase();
        console.log(str1);
        str2 = stu.toLowerCase();
        console.log(str2);
        str3 = stu.charAt(3);
        console.log(str3);
        str4 = stu.indexOf('ga',3);
        console.log(str4);
        str5 = stu.concat(' is')
        console.log(str5);
        str6 = stu.includes('in',4);
        console.log(str6);
        str7 = stu.replace('playings','plays');
        console.log(str7);
        str8 = stu.search('ga');
        console.log(str8);
        str9 =stu.trim();
        console.log(str9);
        str10 = stu.substr(0,3);
        console.log(str10);
        str11 = stu.split('a');
        console.log(str11);
        str12 = stu.split('r',2);
        console.log(str12);
        console.log('=======================================================')
    